version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - "3306:3306"
    environment:
      - MARIADB_USER=matomo
      - MARIADB_DATABASE=matomo
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local